### ISSUE TITLE
Current Wiki JSON Dump not tar.gz

### ISSUE THREAD

**Issue by smithGit** [ValterVB/VBot#1]
Thanks for a great contribution to the .Net use of Wikidata!  The wikidata JSON dump available from http://dumps.wikimedia.org/other/wikidata/ is 20150427.json.gz - not the tar.gz format.  item = JsonConvert.DeserializeObject failed with "unexpected character encountered."

**Comment by ValterVB** [comment]
You must unpacking the file, you can use [7-zip](http://www.7-zip.org/), I have also modified the source with correct file name.

**Comment by smithGit** [comment]
Thank you for your prompt attention to this.  I am unpacking the .gz file now and will report back when completed.  This is my first attempt to access the Wikidata dump directly.  My project is to focus on items that are of historical interest.

**Comment by smithGit** [comment]
It works!  I am really thrilled.  The unpacked JSON text file if 44.009 gigabytes, but it is being read successfully.  Thanks again and I look forward to using this resource more extensively.
